# Generated by Django 4.1.2 on 2023-07-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_address_remove_booking_user_booking_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
