# Generated by Django 4.1.2 on 2023-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
