# Generated by Django 4.1.2 on 2023-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
