# Generated by Django 4.1.2 on 2023-07-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_address_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=250, null=True)),
                ('message', models.TextField(null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('responded', 'responded'), ('completed', 'completed')], default='new', max_length=15)),
            ],
        ),
    ]
